package org.mybatis.dao;

import org.mybatis.cdi.Mapper;
import org.mybatis.model.Computer;

import java.util.List;

@Mapper
public interface ComputerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPUTER
     *
     * @mbg.generated Wed Apr 08 14:38:20 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPUTER
     *
     * @mbg.generated Wed Apr 08 14:38:20 EEST 2020
     */
    int insert(Computer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPUTER
     *
     * @mbg.generated Wed Apr 08 14:38:20 EEST 2020
     */
    Computer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPUTER
     *
     * @mbg.generated Wed Apr 08 14:38:20 EEST 2020
     */
    List<Computer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPUTER
     *
     * @mbg.generated Wed Apr 08 14:38:20 EEST 2020
     */
    int updateByPrimaryKey(Computer record);
}