package org.mybatis.dao;

import org.mybatis.cdi.Mapper;
import org.mybatis.model.Computer;
import org.mybatis.model.Manufacturer;

import java.util.List;

@Mapper
public interface ManufacturerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANUFACTURER
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANUFACTURER
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    int insert(Manufacturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANUFACTURER
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    Manufacturer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANUFACTURER
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    List<Manufacturer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANUFACTURER
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    int updateByPrimaryKey(Manufacturer record);
}