package org.mybatis.dao;

import org.mybatis.cdi.Mapper;
import org.mybatis.model.Computer;
import org.mybatis.model.Processor;

import java.util.List;

@Mapper
public interface ProcessorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROCESSOR
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROCESSOR
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    int insert(Processor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROCESSOR
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    Processor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROCESSOR
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    List<Processor> selectAll();

    void setComputers(List<Computer> computerList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROCESSOR
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    int updateByPrimaryKey(Processor record);
}