package org.mybatis.dao;

import org.mybatis.model.Processor;

import java.util.List;

public interface ProcessorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROCESSOR
     *
     * @mbg.generated Wed Apr 08 14:38:20 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROCESSOR
     *
     * @mbg.generated Wed Apr 08 14:38:20 EEST 2020
     */
    int insert(Processor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROCESSOR
     *
     * @mbg.generated Wed Apr 08 14:38:20 EEST 2020
     */
    Processor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROCESSOR
     *
     * @mbg.generated Wed Apr 08 14:38:20 EEST 2020
     */
    List<Processor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROCESSOR
     *
     * @mbg.generated Wed Apr 08 14:38:20 EEST 2020
     */
    int updateByPrimaryKey(Processor record);
}