package org.mybatis.model;

import java.util.List;
import java.util.Objects;

public class Computer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.ID
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.NAME
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    private String name;

    private Manufacturer manufacturer;

    private List<Processor> processors;

    public void setProcessors(List<Processor> processorList) {
        this.processors = processorList;
    }

    public Manufacturer getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(Manufacturer manufacturer) {
        this.manufacturer = manufacturer;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.MANUFACTURER_ID
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    private Integer manufacturerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.ID
     *
     * @return the value of PUBLIC.COMPUTER.ID
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.ID
     *
     * @param id the value for PUBLIC.COMPUTER.ID
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.NAME
     *
     * @return the value of PUBLIC.COMPUTER.NAME
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.NAME
     *
     * @param name the value for PUBLIC.COMPUTER.NAME
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.MANUFACTURER_ID
     *
     * @return the value of PUBLIC.COMPUTER.MANUFACTURER_ID
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    public Integer getManufacturerId() {
        return manufacturerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.MANUFACTURER_ID
     *
     * @param manufacturerId the value for PUBLIC.COMPUTER.MANUFACTURER_ID
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    public void setManufacturerId(Integer manufacturerId) {
        this.manufacturerId = manufacturerId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        org.mybatis.model.Computer computer = (org.mybatis.model.Computer) o;
        return Objects.equals(id, computer.id) &&
                Objects.equals(name, computer.name);
    }
}