package org.mybatis.model;

import java.util.List;
import java.util.Objects;

public class Processor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROCESSOR.ID
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    private Integer id;

    private List<Computer> computers;

    public void setComputers(List<Computer> computerList) {
        this.computers = computerList;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROCESSOR.NAME
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROCESSOR.ID
     *
     * @return the value of PUBLIC.PROCESSOR.ID
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROCESSOR.ID
     *
     * @param id the value for PUBLIC.PROCESSOR.ID
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROCESSOR.NAME
     *
     * @return the value of PUBLIC.PROCESSOR.NAME
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROCESSOR.NAME
     *
     * @param name the value for PUBLIC.PROCESSOR.NAME
     *
     * @mbg.generated Fri Apr 10 15:44:35 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        org.mybatis.model.Processor processor = (org.mybatis.model.Processor) o;
        return Objects.equals(id, processor.id) &&
                Objects.equals(name, processor.name);
    }
}